--AÑADIR EL ESTADO DEL CLIENTE
--CUSTOMERS CON 0 PEDIDOS(PEPA)
--RELACION ENTRE TABLAS PARA SACAR ORDER_ID, CUSTOMER_NAME, ORDER_TOTAL

SELECT CUST_FIRST_NAME, CUST_LAST_NAME, STATE_NAME
FROM DEMO_CUSTOMERS
FULL OUTER JOIN DEMO_ORDERS
ON DEMO_CUSTOMERS.CUSTOMER_ID = DEMO_ORDERS.CUSTOMER_ID
LEFT JOIN DEMO_STATES
ON DEMO_CUSTOMERS.CUST_STATE = DEMO_STATES.ST
WHERE DEMO_ORDERS.CUSTOMER_ID IS NULL OR DEMO_CUSTOMERS.CUSTOMER_ID IS NULL;