CREATE OR REPLACE TRIGGER log_item_insert
AFTER INSERT
ON DEMO_ORDER_ITEMS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
FECHA_ACTUAL DATE := SYSDATE;
TEXT DEMO_LOGS.text%TYPE := :NEW.ORDER_ID || ' insertado correctamente.';
BEGIN
    UPDATE DEMO_ORDERS 
    SET ORDER_TOTAL = ORDER_TOTAL + (:NEW.UNIT_PRICE * :NEW.QUANTITY)
    WHERE DEMO_ORDERS.ORDER_ID = :NEW.ORDER_ID;
END;