CREATE OR REPLACE TRIGGER log_item_update
AFTER UPDATE
ON DEMO_ORDER_ITEMS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
FECHA_ACTUAL DATE := SYSDATE;
TEXT DEMO_LOGS.text%TYPE := :NEW.ORDER_ID || ' se ha actualizado correctamente.';
BEGIN
    UPDATE DEMO_ORDERS 
    SET ORDER_TOTAL = ORDER_TOTAL - (:OLD.UNIT_PRICE * :OLD.QUANTITY) + (:NEW.UNIT_PRICE * :NEW.QUANTITY)
    WHERE DEMO_ORDERS.ORDER_ID = :OLD.ORDER_ID;
END;