CREATE OR REPLACE TRIGGER log_item_delete
AFTER DELETE
ON DEMO_ORDER_ITEMS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
FECHA_ACTUAL DATE := SYSDATE;
TEXT DEMO_LOGS.text%TYPE := 'Eliminado correctamente.';
BEGIN
    UPDATE DEMO_ORDERS 
    SET ORDER_TOTAL = ORDER_TOTAL - (:OLD.UNIT_PRICE * :OLD.QUANTITY)
    WHERE DEMO_ORDERS.ORDER_ID = :OLD.ORDER_ID;
END;